trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

job:
  job: "DisplayVariablesDev"
  displayName: "Display Dev Variables" 

variables:
  - group: "dev-var"
  - group: "prod-var"

steps:
  - script: |
      echo "My application is $(appname)"
      echo "My environment is $(environment)"
    displayName: "Display Variables"

job:
  job: "DisplayVariablesProd"
  displayName: "Display Prod Variables" 
  
  variables:
  - group: "prod-var"    

steps:
  - script: |
      echo "My application is $(appname)"
      echo "My environment is $(environment)"
    displayName: "Display Variables"  